language: node_js
node_js:
- '13'
script:
- echo 'Build starts!!'
- echo 'Installing Deps!'
- yarn
- echo 'Compiling!'
- yarn build
deploy:
  provider: firebase
  token: jsUa+lWUgTaQrwoAAWoXN1ZdJ5Ae6uvdeiN/PAtJOdgd04jdGPRp3LAGBQPiIgmy2pxNfWaKbLpVp7a227CLYnkpAqblVdDiVoKl3+GPDP3bP1/01boUTaTg6Cim+SOm1QdmQlfrsocrx/hptPDDZOkx5dtNj/F02tv0nYKMpASvp0J/cw8Wzt6jT384ck5GxKW2mQvQyOzK1qAUVBQfYd3hTJ3jthSXzP7hLWH1qtuX61MJz8iy8WXZlrt+UKx5PCKDpnwRNU1IEuWfTEc4ipttV9cYRSroJ8zYMab2eoSyMOUAn71qeeqygVSvwJp9/Db1w1XHwpUhTFkbXrOA4XFJvVTErEwLI+8s9OZ4S3ivvC8DBZg1MPRHGm24J0oY1rozM4PgVO6ALGZsFwgGaLF8ZvfEllb4tdkl4xjQuYyQEfsT51YqemaO1pg95FTjSs79Ns+0ejz1M0qet1p9FDJExPsNOKAlAaYGFrfpZpXuzgxfHuAAxxdbzZoa58RNbGi88MDHGgGlie8oedYL0AIL7wV6z8Rm5/IJXPncCA0RLHlOQs3Jjq144XNAMXS7OyLyus+56RHlgVxDRBxMXP4jtbIYMc48lHHxd/sAXCEC7aBLrMBKMG+eF4Nz3045vp5Z89eWww24KwWIlUIDhkmWefGsOG3lLJNVoA+cMKI=
  project: prayer-phone
  edge: true # opt in to dpl v2
